name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .

      - name: Run tests with pytest
        run: pytest
